#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Software to run main loop of software
#
# Author : Damian Karbowiak
# Company:
#
# Date   : 13/07/2017
#
#-------------------------------------------------------------------------------------------------------------#
# Import library
#-------------------------------------------------------------------------------------------------------------#
from dk_wm import VentilatorMonitor

ventilator = VentilatorMonitor.VentilatorMonitor()
ventilator.main()